name: Build and Push Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: false
        default: ''
      latest:
        type: boolean
        description: Latest Version
        required: false
        default: true
      sdk_path:
        description: https://docs.gaganode.com/sdk/pc-sdk.html
        required: false
        default: /0.0.600/gaganode_pro-0_0_600.tar.gz

env:
  GITHUB_CR_REPO: ghcr.io/${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker tags
        run: |
          ver="${{ github.event.inputs.version }}"
          tags="type=raw,value=${ver:-dev}"
          if [ -n "${{ github.event.inputs.latest }}" ]; then
            tags=$({
              echo "$tags"
              echo "type=raw,value=latest"
            })
          fi
          echo "VERSION=$ver" >> $GITHUB_ENV
          {
            echo 'ALL_TAGS<<EOF'
            echo "$tags"
            echo EOF
          } >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_CR_REPO }}
          tags: ${{ env.ALL_TAGS }}

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            APP_VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
